export const GET_PEOPLE_REQUESTED = 'GET_PEOPLE_REQUESTED';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_IMG_REQUESTED = 'GET_IMG_REQUESTED';
export const GET_IMG_SUCCESS = 'GET_IMG_SUCCESS';
export const PEOPLE_FAILED = 'PEOPLE_FAILED';