export const GET_PEOPLE_REQUESTED = 'GET_PEOPLE_REQUESTED';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const CHANGE_INPUTVALUE_REQUESTED = 'CHANGE_INPUTVALUE_REQUESTED';
export const CHANGE_INPUTVALUE_SUCCESS = 'CHANGE_INPUTVALUE_SUCCESS';
export const PEOPLE_FAILED = 'PEOPLE_FAILED';